config/routes.rb
Rails.application.routes.draw do
  
  resources :tablas, only: [:index, :create, :destroy, :update, :show]

  namespace :api, defaults: {format: 'json'} do
  resources :tablas, only: [:index, :create, :destroy, :update, :show]
end
  root 'tablas#index'

end

app/models/tabla.rb
class Tabla < ActiveRecord::Base
end

app/controllers/api/tablas_controller.rb
class Api::TablasController < ApplicationController

	def index
    @tablas = Tabla.all
    render json: @tablas
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tablas_controller.rb
class TablasController < ApplicationController
  before_action :set_tabla, only: [:show, :edit, :update, :destroy]

  # GET /tablas
  # GET /tablas.json
  def index
    @tablas = Tabla.all
    render json: @tablas


  end

  # GET /tablas/1
  # GET /tablas/1.json
  def show
  end

  # GET /tablas/new
  def new
    @tabla = Tabla.new
    
  end

  # GET /tablas/1/edit
  def edit
  end

  # POST /tablas
  # POST /tablas.json
  def create
    @tabla = Tabla.new(tabla_params)

    respond_to do |format|
      if @tabla.save
        format.html { redirect_to @tabla, notice: 'Tabla was successfully created.' }
        format.json { render :show, status: :created, location: @tabla }
      else
        format.html { render :new }
        format.json { render json: @tabla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tablas/1
  # PATCH/PUT /tablas/1.json
  def update
    respond_to do |format|
      if @tabla.update(tabla_params)
        format.html { redirect_to @tabla, notice: 'Tabla was successfully updated.' }
        format.json { render :show, status: :ok, location: @tabla }
      else
        format.html { render :edit }
        format.json { render json: @tabla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tablas/1
  # DELETE /tablas/1.json
  def destroy
    @tabla.destroy
    respond_to do |format|
      format.html { redirect_to tablas_url, notice: 'Tabla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabla
      @tabla = Tabla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tabla_params
      params.require(:tabla).permit(:rango, :sintoma, :valor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tablas_helper.rb
module TablasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webservice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tablas/_form.html.erb
<%= form_for(@tabla) do |f| %>
  <% if @tabla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tabla.errors.count, "error") %> prohibited this tabla from being saved:</h2>

      <ul>
      <% @tabla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rango %><br>
    <%= f.text_field :rango %>
  </div>
  <div class="field">
    <%= f.label :sintoma %><br>
    <%= f.text_field :sintoma %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tablas/edit.html.erb
<h1>Editing Tabla</h1>

<%= render 'form' %>

<%= link_to 'Show', @tabla %> |
<%= link_to 'Back', tablas_path %>

app/views/tablas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tablas</h1>

<table>
  <thead>
    <tr>
      <th>Rango</th>
      <th>Sintoma</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tablas.each do |tabla| %>
      <tr>
        <td><%= tabla.rango %></td>
        <td><%= tabla.sintoma %></td>
        <td><%= tabla.valor %></td>
        <td><%= link_to 'Show', tabla %></td>
        <td><%= link_to 'Edit', edit_tabla_path(tabla) %></td>
        <td><%= link_to 'Destroy', tabla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tabla', new_tabla_path %>

app/views/tablas/new.html.erb
<h1>New Tabla</h1>

<%= render 'form' %>

<%= link_to 'Back', tablas_path %>

app/views/tablas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rango:</strong>
  <%= @tabla.rango %>
</p>

<p>
  <strong>Sintoma:</strong>
  <%= @tabla.sintoma %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @tabla.valor %>
</p>

<%= link_to 'Edit', edit_tabla_path(@tabla) %> |
<%= link_to 'Back', tablas_path %>